### ISSUE TITLE
Secure password

### ISSUE THREAD

**Issue by Asamaclar** [Microsoft/vsts-rm-documentation#10]
With the actual script, 
returns error with:
SPNCreation.ps1 : Cannot bind parameter 'Password'. Cannot convert the "xxxxxxx" value of type "System.String" to type "System.Security.SecureString"
 + CategoryInfo          : InvalidArgument: (:) [SPNCreation.ps1], ParameterBindingException
 + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,SPNCreation.ps1

Only changing line 7 works fine

before: (bad)
`[String] $password,`

after: (worksfine)
`[System.Security.SecureString] $password,`

**Comment by pavanadepu2** [comment]
Thanks much for reporting the issue. This issue is fixed now.
