### ISSUE TITLE
Deprecated parameter in New-AzureRmADApplication call

### ISSUE THREAD

**Issue by timhargreaves** [Microsoft/vsts-rm-documentation#6]
**Input**:
$azureAdApplication = New-AzureRmADApplication -DisplayName $displayName -HomePage $homePage -IdentifierUris $identifier Uri -Password $password -Verbose

**Output**:
WARNING: Parameter 'Password' is obsolete. New-AzureRmADApplication: The parameter "Password" is being changed from a string to a SecureString in an upcoming breaking change release.

**Comment by yoichinak** [comment]
workaround:
```
$SecurePassword = Read-Host -Prompt "Enter password" -AsSecureString
$azureAdApplication = New-AzureRmADApplication -DisplayName $displayName -HomePage $homePage -IdentifierUris $identifier Uri -Password $SecurePassword -Verbose
```

**Comment by cyrilcathala** [comment]
Thanks yoichinak!
Is there a pull request to update the script somewhere?

**Comment by yoichinak** [comment]
You're welcome :)
https://github.com/Microsoft/vsts-rm-documentation/pull/8 might be better.

**Comment by MarkIannucci** [comment]
Now there are two Pull Requests for this issue.  I submitted #9 also.  @msftgits can you accept one of these PRs so others don't hit the same speed bumps as they're implementing your software?

**Comment by pavanadepu2** [comment]
@MarkIannucci, thanks much for contributing the fix. I have accepted the PR.
